# -*- coding: utf-8 -*-
"""Factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGu8zCxW7XUIGicXbuOZ6Nk5RKdhegJ2
"""

n = 5
fact = 1

for i in range(1, n + 1):
    fact = fact * i

print(f"Factorial of {n} = {fact}")

